version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
      python: 3.9  # Required for AWS SAM CLI
  
  pre_build:
    commands:
      - echo Pre-build phase started
      - mvn clean
      - pip install --upgrade aws-sam-cli
      
  build:
    commands:
      - echo Build phase started
      - mvn test
      - mvn package
      - sam build --debug
      
  post_build:
    commands:
      - echo Build completed
      - sam package --template-file template.yaml --s3-bucket ${ARTIFACT_BUCKET} --output-template-file packaged.yaml
      
artifacts:
  files:
    - target/*.jar
    - packaged.yaml
    - template.yaml
    - appspec.yml
    - .aws-sam/**/*
  discard-paths: no
