version: 0.2

phases:
  install:
    runtime-versions:
      java: java21
      python: 3.9  # Required for AWS SAM CLI
  
  pre_build:
    commands:
      - echo Pre-build phase started on `date`
      - mvn clean
      - pip install --upgrade aws-sam-cli
      
  build:
    commands:
      - echo Build phase started on `date`
      - mvn compile
      - mvn package
      - sam build
      
  test:
    commands:
      - echo Test phase started on `date`
      - mvn test
      
  post_build:
    commands:
      - echo Build completed on `date`
      - sam package --template-file template.yaml --s3-bucket ${ARTIFACT_BUCKET} --output-template-file packaged.yaml
      
artifacts:
  files:
    - target/*.jar
    - packaged.yaml
    - template.yaml
    - appspec.yml
  discard-paths: no
